export default function Rod() {
    // 내경/기호 표 (제품설명 초반 표)
    return (
        <table className="rod compact">
            <thead>
                <tr>
                    <th className="line">
                        <span>기호</span>
                        <span>내경</span>
                    </th>
                    <th>A</th>
                    <th>BT</th>
                    <th>D</th>
                    <th>E</th>
                    <th>FB</th>
                    <th>FG</th>
                    <th>M</th>
                    <th>R</th>
                    <th>G</th>
                    <th>L</th>
                    <th>Q</th>
                    <th>C</th>
                    <th>B</th>
                    <th>P</th>
                    <th>RR</th>
                    <th>U</th>
                    <th>K</th>
                    <th>S</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>ø32</td>
                    <td>25</td>
                    <td>6.5</td>
                    <td>14</td>
                    <td>□62</td>
                    <td>ø6.6</td>
                    <td>ø11</td>
                    <td>M12x1.75P</td>
                    <td>54</td>
                    <td>ø18</td>
                    <td>14</td>
                    <td>12</td>
                    <td>□47</td>
                    <td>10</td>
                    <td>28</td>
                    <td>64</td>
                    <td>7</td>
                    <td>PT 1/8"</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>ø40</td>
                    <td>30</td>
                    <td>8.6</td>
                    <td>19</td>
                    <td>□69</td>
                    <td>ø9</td>
                    <td>ø14</td>
                    <td>M16x2P</td>
                    <td>55</td>
                    <td>ø22.4</td>
                    <td>16</td>
                    <td>12</td>
                    <td>□52</td>
                    <td>10</td>
                    <td>27</td>
                    <td>65</td>
                    <td>7</td>
                    <td>PT 1/4"</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>ø50</td>
                    <td>35</td>
                    <td>10.8</td>
                    <td>24</td>
                    <td>□79</td>
                    <td>ø11</td>
                    <td>ø17.5</td>
                    <td>M20x2.5P</td>
                    <td>60</td>
                    <td>ø28</td>
                    <td>19</td>
                    <td>13</td>
                    <td>□58</td>
                    <td>11</td>
                    <td>28</td>
                    <td>71</td>
                    <td>8</td>
                    <td>PT 1/4"</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>ø63</td>
                    <td>40</td>
                    <td>13</td>
                    <td>30</td>
                    <td>□94</td>
                    <td>ø14</td>
                    <td>ø20</td>
                    <td>M27x3P</td>
                    <td>67</td>
                    <td>ø35</td>
                    <td>24</td>
                    <td>13</td>
                    <td>□69</td>
                    <td>13</td>
                    <td>30</td>
                    <td>80</td>
                    <td>9</td>
                    <td>PT 3/8"</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>ø80</td>
                    <td>45</td>
                    <td>15.2</td>
                    <td>41</td>
                    <td>□114</td>
                    <td>ø16</td>
                    <td>ø23</td>
                    <td>M30x3.5P</td>
                    <td>78</td>
                    <td>ø45</td>
                    <td>25</td>
                    <td>18</td>
                    <td>□86</td>
                    <td>17</td>
                    <td>35</td>
                    <td>95</td>
                    <td>14</td>
                    <td>PT 3/8"</td>
                    <td>15</td>
                </tr>
                <tr>
                    <td>ø100</td>
                    <td>50</td>
                    <td>18</td>
                    <td>50</td>
                    <td>□140</td>
                    <td>ø18</td>
                    <td>ø26</td>
                    <td>M39x4P</td>
                    <td>110</td>
                    <td>ø55</td>
                    <td>35</td>
                    <td>25</td>
                    <td>□106</td>
                    <td>20</td>
                    <td>50</td>
                    <td>130</td>
                    <td>16</td>
                    <td>PT 1/2"</td>
                    <td>18</td>
                </tr>
                <tr>
                    <td>ø125</td>
                    <td>55</td>
                    <td>22</td>
                    <td>65</td>
                    <td>□170</td>
                    <td>ø22</td>
                    <td>ø32</td>
                    <td>M48x5P</td>
                    <td>155</td>
                    <td>ø70</td>
                    <td>44</td>
                    <td>38</td>
                    <td>□132</td>
                    <td>25</td>
                    <td>73</td>
                    <td>180</td>
                    <td>21</td>
                    <td>PT 1/2"</td>
                    <td>23</td>
                </tr>
            </tbody>
        </table>
    )
}