export default function RodNut() {
  return (
    <table className="rodNut standard">
      <thead>
        <tr>
          <th rowSpan={2} className="line">
            <span>기호</span>
            <span>내경</span>
          </th>
          <th colSpan={4}>B형</th>
          <th colSpan={4}>C형</th>
        </tr>
        <tr>
          <th>M</th>
          <th>B</th>
          <th>C</th>
          <th>H</th>
          <th>M</th>
          <th>B</th>
          <th>C</th>
          <th>H</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>ø40</th>
          <td>M20x1.5P</td>
          <td>30</td>
          <td>34</td>
          <td>12</td>
          <td>M16x1.5P</td>
          <td>24</td>
          <td>27</td>
          <td>10</td>
        </tr>
        <tr>
          <th>ø50</th>
          <td>M24x1.5P</td>
          <td>36</td>
          <td>41</td>
          <td>12</td>
          <td>M20x1.5P</td>
          <td>30</td>
          <td>34</td>
          <td>12</td>
        </tr>
        <tr>
          <th>ø63</th>
          <td>M30x1.5P</td>
          <td>41</td>
          <td>47</td>
          <td>12</td>
          <td>M24x1.5P</td>
          <td>36</td>
          <td>41</td>
          <td>12</td>
        </tr>
        <tr>
          <th>ø80</th>
          <td>M39x1.5P</td>
          <td>ø58</td>
          <td>6</td>
          <td>12</td>
          <td>M30x1.5P</td>
          <td>41</td>
          <td>47</td>
          <td>12</td>
        </tr>
        <tr>
          <th>ø100</th>
          <td>M48x1.5P</td>
          <td>ø70</td>
          <td>6</td>
          <td>15</td>
          <td>M39x1.5P</td>
          <td>ø58</td>
          <td>6</td>
          <td>12</td>
        </tr>
        <tr>
          <th>ø125</th>
          <td>M64x2P</td>
          <td>ø84</td>
          <td>7</td>
          <td>20</td>
          <td>M48x1.5P</td>
          <td>ø70</td>
          <td>6</td>
          <td>15</td>
        </tr>
        <tr>
          <th>ø140</th>
          <td>M72x2P</td>
          <td>ø108</td>
          <td>8</td>
          <td>24</td>
          <td>M56x2P</td>
          <td>ø74</td>
          <td>7</td>
          <td>17</td>
        </tr>
        <tr>
          <th>ø150</th>
          <td>M76x2P</td>
          <td>ø108</td>
          <td>8</td>
          <td>24</td>
          <td>M60x2P</td>
          <td>ø84</td>
          <td>7</td>
          <td>20</td>
        </tr>
        <tr>
          <th>ø160</th>
          <td>M80x2P</td>
          <td>ø115</td>
          <td>8</td>
          <td>24</td>
          <td>M64x2P</td>
          <td>ø84</td>
          <td>7</td>
          <td>20</td>
        </tr>
        <tr>
          <th>ø180</th>
          <td>M95x2P</td>
          <td>ø128</td>
          <td>8</td>
          <td>27</td>
          <td>M72x2P</td>
          <td>ø108</td>
          <td>8</td>
          <td>24</td>
        </tr>
        <tr>
          <th>ø200</th>
          <td>M100x2P</td>
          <td>ø135</td>
          <td>8</td>
          <td>27</td>
          <td>M80x2P</td>
          <td>ø115</td>
          <td>8</td>
          <td>24</td>
        </tr>
        <tr>
          <th>ø250</th>
          <td>M130x2P</td>
          <td>ø180</td>
          <td>8</td>
          <td>30</td>
          <td>M100x2P</td>
          <td>ø135</td>
          <td>8</td>
          <td>27</td>
        </tr>
      </tbody>
    </table>
  )
}