export default function SealPartsDiagram() {
    // 패킹 부품도
    return (
        <table className="seal-parts-diagram double">
            <thead>
                <tr>
                    <th colSpan={2}>NO</th>
                    <th>10</th>
                    <th>11</th>
                    <th>12</th>
                    <th>13</th>
                    <th>14</th>
                    <th>15</th>
                    <th>16</th>
                    <th>17</th>
                    <th>18</th>
                </tr>
                <tr>
                    <th colSpan={2}>명칭</th>
                    <td>더스트씰</td>
                    <td>U-패킹</td>
                    <td>오링</td>
                    <td>더스트씰</td>
                    <td>U-패킹</td>
                    <td>오링</td>
                    <td>오링</td>
                    <td>오링</td>
                    <td>오링</td>
                </tr>
                <tr>
                    <th colSpan={2}>재질</th>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                    <td>NBR</td>
                </tr>
                <tr>
                    <th colSpan={2}>수량</th>
                    <td>1</td>
                    <td>2</td>
                    <td>2</td>
                    <td>1</td>
                    <td>2</td>
                    <td>2</td>
                    <td>1</td>
                    <td>2</td>
                    <td>1</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th rowSpan={5}>기종</th>
                    <td>10형</td>
                    <td>LBH28</td>
                    <td>USH28</td>
                    <td>G40</td>
                    <td>LBH53</td>
                    <td>USH53</td>
                    <td>G60</td>
                    <td>P39</td>
                    <td>P10A(EA)</td>
                    <td>P53</td>
                </tr>
                <tr>
                    <td>20형</td>
                    <td>LBH40</td>
                    <td>USH40</td>
                    <td>G60</td>
                    <td>LBH75</td>
                    <td>USH75</td>
                    <td>G95</td>
                    <td>P55</td>
                    <td>P15</td>
                    <td>P80</td>
                </tr>
                <tr>
                    <td>30형</td>
                    <td>LBH45</td>
                    <td>USH45</td>
                    <td>G75</td>
                    <td>LBH90</td>
                    <td>USH90</td>
                    <td>G115</td>
                    <td>P70</td>
                    <td>P18</td>
                    <td>P100</td>
                </tr>
                <tr>
                    <td>40형</td>
                    <td>LBH53</td>
                    <td>USH53</td>
                    <td>G85</td>
                    <td>LBH106</td>
                    <td>USH106</td>
                    <td>G130</td>
                    <td>P80</td>
                    <td>P18</td>
                    <td>P115</td>
                </tr>
                <tr>
                    <td>50형</td>
                    <td>LBH60</td>
                    <td>USH60</td>
                    <td>G95</td>
                    <td>LBH118</td>
                    <td>USH118</td>
                    <td>G145</td>
                    <td>P90</td>
                    <td>P18</td>
                    <td>P130</td>
                </tr>
            </tbody>
        </table>
    )
}