export default function Rod() {
    // 내경/기호 표 (제품설명 초반 표)
    return (
        <table className="rod round">
            <thead>
                <tr>
                    <th rowSpan={2}>
                        <span>기호</span>
                        <span>내경</span>
                    </th>
                    <th>A</th>
                    <th>B</th>
                    <th>C</th>
                    <th>M</th>
                    <th>G</th>
                    <th>E</th>
                    <th>EE</th>
                    <th>CC</th>
                    <th>CD</th>
                    <th>CE</th>
                    <th>CF</th>
                    <th>CG</th>
                    <th>CR</th>
                    <th>D1</th>
                    <th>D2</th>
                    <th>H</th>
                    <th>K</th>
                    <th>P</th>
                    <th>Q</th>
                    <th>U</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>ø40</td>
                    <td>30</td>
                    <td>17</td>
                    <td>37</td>
                    <td>M18x1.5P</td>
                    <td>ø20</td>
                    <td>ø55</td>
                    <td>ø90</td>
                    <td>33</td>
                    <td>ø25</td>
                    <td>R27.5</td>
                    <td>23</td>
                    <td>-</td>
                    <td>252</td>
                    <td>40</td>
                    <td>45</td>
                    <td>80</td>
                    <td>PF 1/2"</td>
                    <td>18</td>
                    <td>25</td>
                    <td>GE25ES</td>
                </tr>
                <tr>
                    <td>ø250</td>
                    <td>160</td>
                    <td>41</td>
                    <td>124</td>
                    <td>M120x2P</td>
                    <td>ø160</td>
                    <td>ø280</td>
                    <td>ø432</td>
                    <td>140</td>
                    <td>ø110</td>
                    <td>R150</td>
                    <td>80</td>
                    <td>160</td>
                    <td>789</td>
                    <td>105</td>
                    <td>105</td>
                    <td>274</td>
                    <td>PF 1"</td>
                    <td>40</td>
                    <td>40</td>
                    <td>GE110ES</td>
                </tr>
            </tbody>
        </table>
    )
}