export default function RoundRod2() {
    return (
        <table className="rod2 round">
            <thead>
                <tr>
                    <th className="line">
                        <span>기호</span>
                        <span>내경</span>
                    </th>
                    <th>B</th>
                    <th>B1</th>
                    <th>B2</th>
                    <th>B3</th>
                    <th>D1</th>
                    <th>D2</th>
                    <th>L1</th>
                    <th>L2</th>
                    <th>L3</th>
                    <th>L4</th>
                    <th>R</th>
                    <th>T1</th>
                    <th>M</th>
                    <th>SR</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>Ø40</th>
                    <td>GE25ES</td>
                    <td>23</td>
                    <td>20</td>
                    <td>28</td>
                    <td>M18x1.5P</td>
                    <td>Ø25</td>
                    <td>65</td>
                    <td>25</td>
                    <td>30</td>
                    <td>48</td>
                    <td>R28</td>
                    <td>32</td>
                    <td>M8</td>
                    <td>R42</td>
                </tr>
                <tr>
                    <th>Ø50</th>
                    <td>GE30ES</td>
                    <td>28</td>
                    <td>22</td>
                    <td>34</td>
                    <td>M24x1.5P</td>
                    <td>Ø30</td>
                    <td>75</td>
                    <td>30</td>
                    <td>34</td>
                    <td>54</td>
                    <td>R32</td>
                    <td>37</td>
                    <td>M8</td>
                    <td>R47</td>
                </tr>
                <tr>
                    <th>Ø63</th>
                    <td>GE35ES</td>
                    <td>30</td>
                    <td>25</td>
                    <td>44</td>
                    <td>M30x1.5P</td>
                    <td>Ø35</td>
                    <td>90</td>
                    <td>40</td>
                    <td>42</td>
                    <td>66</td>
                    <td>R39</td>
                    <td>47</td>
                    <td>M8</td>
                    <td>R55</td>
                </tr>
                <tr>
                    <th>Ø80</th>
                    <td>GE40ES</td>
                    <td>35</td>
                    <td>28</td>
                    <td>55</td>
                    <td>M39x1.5P</td>
                    <td>Ø40</td>
                    <td>105</td>
                    <td>45</td>
                    <td>50</td>
                    <td>78</td>
                    <td>R47</td>
                    <td>57</td>
                    <td>M8</td>
                    <td>R62</td>
                </tr>
                <tr>
                    <th>Ø100</th>
                    <td>GE50ES</td>
                    <td>40</td>
                    <td>35</td>
                    <td>70</td>
                    <td>M48x1.5P</td>
                    <td>Ø50</td>
                    <td>135</td>
                    <td>55</td>
                    <td>63</td>
                    <td>90</td>
                    <td>R58</td>
                    <td>77</td>
                    <td>M10</td>
                    <td>R75</td>
                </tr>
                <tr>
                    <th>Ø125</th>
                    <td>GE60ES</td>
                    <td>50</td>
                    <td>44</td>
                    <td>87</td>
                    <td>M64x2P</td>
                    <td>Ø60</td>
                    <td>170</td>
                    <td>65</td>
                    <td>70</td>
                    <td>118</td>
                    <td>R65</td>
                    <td>98</td>
                    <td>M10</td>
                    <td>R90</td>
                </tr>
                <tr>
                    <th>Ø140</th>
                    <td>GE70ES</td>
                    <td>55</td>
                    <td>49</td>
                    <td>105</td>
                    <td>M80x2P</td>
                    <td>Ø70</td>
                    <td>195</td>
                    <td>75</td>
                    <td>83</td>
                    <td>130</td>
                    <td>R77</td>
                    <td>113</td>
                    <td>M12</td>
                    <td>R105</td>
                </tr>
                <tr>
                    <th>Ø150</th>
                    <td>GE70ES</td>
                    <td>55</td>
                    <td>49</td>
                    <td>105</td>
                    <td>M80x2P</td>
                    <td>Ø70</td>
                    <td>195</td>
                    <td>75</td>
                    <td>83</td>
                    <td>130</td>
                    <td>R77</td>
                    <td>113</td>
                    <td>M12</td>
                    <td>R105</td>
                </tr>
                <tr>
                    <th>Ø160</th>
                    <td>GE80ES</td>
                    <td>60</td>
                    <td>55</td>
                    <td>125</td>
                    <td>M90x2P</td>
                    <td>Ø80</td>
                    <td>210</td>
                    <td>80</td>
                    <td>95</td>
                    <td>152</td>
                    <td>R88</td>
                    <td>123</td>
                    <td>M16</td>
                    <td>R120</td>
                </tr>
                <tr>
                    <th>Ø180</th>
                    <td>GE90ES</td>
                    <td>65</td>
                    <td>60</td>
                    <td>150</td>
                    <td>M100x2P</td>
                    <td>Ø90</td>
                    <td>250</td>
                    <td>90</td>
                    <td>113</td>
                    <td>162</td>
                    <td>R103</td>
                    <td>143</td>
                    <td>M16</td>
                    <td>R130</td>
                </tr>
                <tr>
                    <th>Ø200</th>
                    <td>GE100ES</td>
                    <td>70</td>
                    <td>70</td>
                    <td>170</td>
                    <td>M110x2P</td>
                    <td>Ø100</td>
                    <td>275</td>
                    <td>105</td>
                    <td>125</td>
                    <td>172</td>
                    <td>R115</td>
                    <td>155</td>
                    <td>M20</td>
                    <td>R150</td>
                </tr>
                <tr>
                    <th>Ø250</th>
                    <td>GE110ES</td>
                    <td>80</td>
                    <td>70</td>
                    <td>180</td>
                    <td>M120x2P</td>
                    <td>Ø110</td>
                    <td>300</td>
                    <td>115</td>
                    <td>142.5</td>
                    <td>194</td>
                    <td>R132.5</td>
                    <td>165</td>
                    <td>M20</td>
                    <td>R160</td>
                </tr>
            </tbody>
        </table>
    )
}