export default function HighRodNut() {
  return (
    <table className="rodNut high-pressure">
      <thead>
        <tr>
          <th rowSpan={2} className="line">
            <span>기호</span>
            <span>내경</span>
          </th>
          <th>M</th>
          <th>B</th>
          <th>C</th>
          <th>H</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>Ø40</th>
          <td>M20x1.5P</td>
          <td>30</td>
          <td>34</td>
          <td>12</td>
        </tr>
        <tr>
          <th>Ø50</th>
          <td>M24x1.5P</td>
          <td>36</td>
          <td>41</td>
          <td>12</td>
        </tr>
        <tr>
          <th>Ø63</th>
          <td>M30x1.5P</td>
          <td>41</td>
          <td>47</td>
          <td>12</td>
        </tr>
        <tr>
          <th>Ø80</th>
          <td>M39x1.5P</td>
          <td>Ø58</td>
          <td>6</td>
          <td>12</td>
        </tr>
        <tr>
          <th>Ø100</th>
          <td>M48x1.5P</td>
          <td>Ø70</td>
          <td>6</td>
          <td>12</td>
        </tr>
        <tr>
          <th>Ø125</th>
          <td>M64x2P</td>
          <td>Ø84</td>
          <td>7</td>
          <td>15</td>
        </tr>
        <tr>
          <th>Ø140</th>
          <td>M72x2P</td>
          <td>Ø108</td>
          <td>8</td>
          <td>24</td>
        </tr>
        <tr>
          <th>Ø150</th>
          <td>M76x2P</td>
          <td>Ø108</td>
          <td>8</td>
          <td>24</td>
        </tr>
        <tr>
          <th>Ø160</th>
          <td>M80x2P</td>
          <td>Ø115</td>
          <td>8</td>
          <td>24</td>
        </tr>
      </tbody>
    </table>
  )
}