export default function RecRodNut() {
  return (
    <table className="rodNut rectangular">
      <thead>
        <tr>
          <th rowSpan={2} className="line">
            <span>기호</span>
            <span>내경</span>
          </th>
          <th colSpan={5}>A형</th>
          <th colSpan={5}>B형</th>
        </tr>
        <tr>
          <th>M</th>
          <th>B</th>
          <th>C</th>
          <th>H</th>
          <th>P</th>
          <th>M</th>
          <th>B</th>
          <th>C</th>
          <th>H</th>
          <th>P</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>ø40</th>
          <td>M24x1.5P</td>
          <td>36</td>
          <td>41.6</td>
          <td>19</td>
          <td>-</td>
          <td>M20x1.5P</td>
          <td>30</td>
          <td>34.6</td>
          <td>16</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø50</th>
          <td>M30x1.5P</td>
          <td>46</td>
          <td>53.1</td>
          <td>24</td>
          <td>-</td>
          <td>M24x1.5P</td>
          <td>36</td>
          <td>41.6</td>
          <td>19</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø63</th>
          <td>M39x1.5P</td>
          <td>60</td>
          <td>69.3</td>
          <td>31</td>
          <td>-</td>
          <td>M30x1.5P</td>
          <td>46</td>
          <td>53.1</td>
          <td>24</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø80</th>
          <td>M48x1.5P</td>
          <td>75</td>
          <td>86.5</td>
          <td>38</td>
          <td>-</td>
          <td>M39x1.5P</td>
          <td>60</td>
          <td>69.3</td>
          <td>31</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø100</th>
          <td>M64x2P</td>
          <td>95</td>
          <td>110</td>
          <td>51</td>
          <td>-</td>
          <td>M48x1.5P</td>
          <td>75</td>
          <td>86.5</td>
          <td>38</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø125</th>
          <td>M80x2P</td>
          <td>115</td>
          <td>133</td>
          <td>64</td>
          <td>-</td>
          <td>M64x2P</td>
          <td>95</td>
          <td>110</td>
          <td>51</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø140</th>
          <td>M95x2P</td>
          <td>135</td>
          <td>156</td>
          <td>76</td>
          <td>-</td>
          <td>M72x2P</td>
          <td>105</td>
          <td>121</td>
          <td>58</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø150</th>
          <td>M100x2P</td>
          <td>ø150</td>
          <td>ø15</td>
          <td>80</td>
          <td>18</td>
          <td>M80x2P</td>
          <td>115</td>
          <td>133</td>
          <td>64</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø180</th>
          <td>M120x2P</td>
          <td>ø180</td>
          <td>ø15</td>
          <td>96</td>
          <td>18</td>
          <td>M95x2P</td>
          <td>135</td>
          <td>156</td>
          <td>76</td>
          <td>-</td>
        </tr>
        <tr>
          <th>ø200</th>
          <td>M130x2P</td>
          <td>ø200</td>
          <td>ø20</td>
          <td>104</td>
          <td>25</td>
          <td>M100x2P</td>
          <td>ø150</td>
          <td>ø15</td>
          <td>80</td>
          <td>18</td>
        </tr>
        <tr>
          <th>ø224</th>
          <td>M150x2P</td>
          <td>ø230</td>
          <td>ø20</td>
          <td>120</td>
          <td>25</td>
          <td>M120x2P</td>
          <td>ø180</td>
          <td>ø15</td>
          <td>96</td>
          <td>18</td>
        </tr>
        <tr>
          <th>ø250</th>
          <td>M170x3P</td>
          <td>ø260</td>
          <td>ø20</td>
          <td>138</td>
          <td>25</td>
          <td>M130x2P</td>
          <td>ø200</td>
          <td>ø20</td>
          <td>104</td>
          <td>25</td>
        </tr>
      </tbody>
    </table>
  )
}